web/router.ex
defmodule PhxChat.Router do
  use PhxChat.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhxChat do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/chat", ChatController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhxChat do
  #   pipe_through :api
  # end
end

lib/phx_chat/endpoint.ex
defmodule PhxChat.Endpoint do
  use Phoenix.Endpoint, otp_app: :phx_chat

  socket "/socket", PhxChat.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :phx_chat, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_phx_chat_key",
    signing_salt: "3DfGHwpb"

  plug PhxChat.Router
end

lib/phx_chat/repo.ex
defmodule PhxChat.Repo do
  use Ecto.Repo, otp_app: :phx_chat
end

web/models/message.ex
defmodule PhxChat.Message do
  use PhxChat.Web, :model

  schema "messages" do
    field :content, :string
    field :room, :string
    field :user, :string

    timestamps
  end

  @required_fields ~w(content room user)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/chat_controller.ex
defmodule PhxChat.ChatController do
  use PhxChat.Web, :controller
  import Ecto.Query
  alias PhxChat.Repo
  alias PhxChat.Message

  def show(conn, params) do
    room = params["join"]["room"]
    query = from m in Message,
      where: ilike(m.room, "rooms:" <> room),
      order_by: m.inserted_at,
      select: m
    messages = Repo.all(query)
    render conn, "show.html", room: room, username: params["join"]["username"], messages: messages
  end
end

web/controllers/page_controller.ex
defmodule PhxChat.PageController do
  use PhxChat.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/chat_view.ex
defmodule PhxChat.ChatView do
  use PhxChat.Web, :view
end

web/views/error_view.ex
defmodule PhxChat.ErrorView do
  use PhxChat.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule PhxChat.LayoutView do
  use PhxChat.Web, :view
end

web/views/page_view.ex
defmodule PhxChat.PageView do
  use PhxChat.Web, :view
end

web/templates/chat/show.html.eex
<div id="chat" data-room="<%= @room %>" data-username="<%= @username %>">
  <div class="messages">
    <div class="log">
      <%= for message <- @messages do %>
        <p>[<%= message.inserted_at %>] <%= message.user %> - <%= message.content %></p>
      <% end %>
    </div>

    <div class="compose">
      <input id="chat_message" type="text" />
    </div>
  </div>

  <div class="users-connected">
  </div>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PHX CHAT!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= @inner %>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<%= form_for @conn, chat_path(@conn, :show), [as: :join, method: :get], fn f -> %>
  <%= text_input f, :username, placeholder: "Your username", required: true %>
  <br/>
  <%= text_input f, :room, value: "lobby", placeholder: "Room", required: true %>
  <br/>
  <%= submit "Join" %>
<% end %>